[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.mypy]
warn_return_any = true
plugins = ["mypy_django_plugin.main"]

[tool.django-stubs]
django_settings_module = "django_alpine_htmx.settings"
